// Need to reduce the amount of includes
#include <arpa/inet.h>
#include <cstring>
#include <curl/curl.h>
#include <fstream>
#include <iostream>
#include <limits>
#include <netinet/in.h>
#include <PcapLiveDeviceList.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/sysinfo.h>
#include <sys/types.h>
#include <SystemUtils.h>
#include <unistd.h>
#include <vector>